/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Role = IDL.Variant({ 'user' : IDL.Null, 'assistant' : IDL.Null });
export const Time = IDL.Int;
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'role' : Role,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'clearHistory' : IDL.Func([], [], []),
  'createConversation' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'getCurrentConversationId' : IDL.Func([], [IDL.Nat], ['query']),
  'getHistory' : IDL.Func([], [IDL.Vec(Message)], ['query']),
  'listConversations' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))],
      ['query'],
    ),
  'sendMessage' : IDL.Func([IDL.Text], [IDL.Text], []),
  'switchConversation' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Role = IDL.Variant({ 'user' : IDL.Null, 'assistant' : IDL.Null });
  const Time = IDL.Int;
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'role' : Role,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'clearHistory' : IDL.Func([], [], []),
    'createConversation' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'getCurrentConversationId' : IDL.Func([], [IDL.Nat], ['query']),
    'getHistory' : IDL.Func([], [IDL.Vec(Message)], ['query']),
    'listConversations' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, IDL.Text))],
        ['query'],
      ),
    'sendMessage' : IDL.Func([IDL.Text], [IDL.Text], []),
    'switchConversation' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };